### ISSUE TITLE
Not displaying tool temperature and infinite loading on some gcodes

### ISSUE THREAD

**Issue by saezels** [Stephan3/dwc2-for-klipper#34]
Just installed Klipper with DWC2.

I really like the interface but I cant get the UI to show my tool temperature. 

I can set the tool temperature and it is displaying on the Printer-LCD just fine. 

Also there are some g-codes that make the UI load infinitely and do not execute (e.g. M105).

I ran Klipper with OctoPrint before without problems. 

[P.S. recognized reiner calmund in the config, greetings from lev ;) ]

**Comment by Stephan3** [comment]
Can you stop Klipper, clear the log(rm /tmp/klippy.log), perform a few actions you described and post the log here?

Probably I broke few things last week.

**Comment by pizzle-d** [comment]
Renaming the extruder0 to extruder should fix it in web_dwc2.py

**Comment by Stephan3** [comment]
@saezels please try latest dwc-for-klipper git, it should work now
@pizzle-d thanks for the quickfind

**Comment by saezels** [comment]
I tinkered too much trying to solve the issue, have to do a fresh install and will Post the log later, thank you

**Comment by saezels** [comment]
Ok my printer runs again. Extruder works with latest git. Infinite loading is still a problem.
Tried "M105" and "ABORT" (after PROBE_CALIBRATE), you can see it in my log. 

Homing , temperature control and others are just working fine. 

klippy.log :

`
Stats 862.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=11977 bytes_read=871391 bytes_retransmit=36 bytes_invalid=0 send_seq=1285 receive_seq=1285 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000365 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.7 pwm=0.000
Stats 863.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=11983 bytes_read=872458 bytes_retransmit=36 bytes_invalid=0 send_seq=1286 receive_seq=1286 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000364 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.4 pwm=0.000
Stats 864.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=11989 bytes_read=873496 bytes_retransmit=36 bytes_invalid=0 send_seq=1287 receive_seq=1287 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000364 heater_bed: target=0 temp=17.7 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.8 pwm=0.000
Stats 865.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=12013 bytes_read=874544 bytes_retransmit=36 bytes_invalid=0 send_seq=1290 receive_seq=1290 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000364 heater_bed: target=0 temp=17.1 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.6 pwm=0.000
Stats 866.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=12037 bytes_read=875606 bytes_retransmit=36 bytes_invalid=0 send_seq=1293 receive_seq=1293 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000365 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.6 pwm=0.000
Stats 867.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=12043 bytes_read=876658 bytes_retransmit=36 bytes_invalid=0 send_seq=1294 receive_seq=1294 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000365 heater_bed: target=0 temp=17.7 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 868.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=12067 bytes_read=877707 bytes_retransmit=36 bytes_invalid=0 send_seq=1297 receive_seq=1297 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.4 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.8 pwm=0.000
M105
DWC2:89522.42 - 192.168.178.29 - GET - /rr_gcode?gcode=M105
M105
passed: M105
Stats 869.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=12091 bytes_read=878769 bytes_retransmit=36 bytes_invalid=0 send_seq=1300 receive_seq=1300 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.6 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.6 pwm=0.000
Stats 870.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=12115 bytes_read=879831 bytes_retransmit=36 bytes_invalid=0 send_seq=1303 receive_seq=1303 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.6 pwm=0.000
Stats 871.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=12121 bytes_read=880855 bytes_retransmit=36 bytes_invalid=0 send_seq=1304 receive_seq=1304 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.5 pwm=0.000
Stats 872.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=12145 bytes_read=881917 bytes_retransmit=36 bytes_invalid=0 send_seq=1307 receive_seq=1307 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.7 pwm=0.000
Stats 873.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000132 mcu_task_stddev=0.000042 bytes_write=12169 bytes_read=882994 bytes_retransmit=36 bytes_invalid=0 send_seq=1310 receive_seq=1310 retransmit_seq=17 srtt=0.004 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.4 pwm=0.000
Stats 874.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000132 mcu_task_stddev=0.000042 bytes_write=12175 bytes_read=884032 bytes_retransmit=36 bytes_invalid=0 send_seq=1311 receive_seq=1311 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.5 pwm=0.000
Stats 875.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000132 mcu_task_stddev=0.000042 bytes_write=12181 bytes_read=885070 bytes_retransmit=36 bytes_invalid=0 send_seq=1312 receive_seq=1312 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 876.6: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000132 mcu_task_stddev=0.000042 bytes_write=12187 bytes_read=886122 bytes_retransmit=36 bytes_invalid=0 send_seq=1313 receive_seq=1313 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000366 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=790.492 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.6 pwm=0.000
DWC2:89549.49 - 192.168.178.29 - GET - /
DWC2:89549.77 - 192.168.178.29 - GET - /rr_disconnect
DWC2:89551.07 - 192.168.178.29 - GET - /rr_connect?password=reprap&time=2019-11-11T17%3A25%3A51
DWC2:89551.53 - 192.168.178.29 - GET - /rr_download?name=0%3A%2Fsys%2Fdwc2settings.json
DWC2:89551.54 - 192.168.178.29 - GET - /rr_filelist?dir=0%3A%2Fmacros&first=0
DWC2:489552.1 - 192.168.178.29 - GET - /rr_filelist?dir=0%3A%2Fmacros&first=0
DWC2:89552.12 - 192.168.178.29 - GET - /rr_config
PROBE_CALIBRATE
DWC2:89562.65 - 192.168.178.29 - GET - /rr_gcode?gcode=PROBE_CALIBRATE
PROBE_CALIBRATE
Stats 909.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000043 bytes_write=12469 bytes_read=920709 bytes_retransmit=36 bytes_invalid=0 send_seq=1353 receive_seq=1353 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000369 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=882.698 buffer_time=0.166 print_stall=0 extruder: target=0 temp=18.3 pwm=0.000
Stats 910.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000043 bytes_write=12810 bytes_read=921862 bytes_retransmit=36 bytes_invalid=0 send_seq=1377 receive_seq=1377 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000370 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=883.698 buffer_time=0.165 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
probe at 100.000,100.000 is z=0.569000
Stats 911.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000043 bytes_write=13108 bytes_read=923017 bytes_retransmit=36 bytes_invalid=0 send_seq=1393 receive_seq=1393 retransmit_seq=17 srtt=0.004 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000371 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=884.687 buffer_time=0.154 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
probe at 100.000,100.000 is z=0.556500
Stats 912.6: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000043 bytes_write=13458 bytes_read=924173 bytes_retransmit=36 bytes_invalid=0 send_seq=1411 receive_seq=1411 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=28 stalled_bytes=0 freq=16000371 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=885.830 buffer_time=0.296 print_stall=0 extruder: target=0 temp=18.3 pwm=0.000
probe at 100.000,100.000 is z=0.576500
Stats 913.6: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000141 mcu_task_stddev=0.000068 bytes_write=13841 bytes_read=925321 bytes_retransmit=36 bytes_invalid=0 send_seq=1430 receive_seq=1430 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=28 stalled_bytes=0 freq=16000371 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=886.969 buffer_time=0.434 print_stall=0 extruder: target=0 temp=18.4 pwm=0.000
probe at 100.000,100.000 is z=0.561500
Stats 914.6: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000141 mcu_task_stddev=0.000068 bytes_write=14224 bytes_read=926482 bytes_retransmit=36 bytes_invalid=0 send_seq=1449 receive_seq=1449 retransmit_seq=17 srtt=0.003 rttvar=0.000 rto=0.025 ready_bytes=28 stalled_bytes=0 freq=16000371 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=888.112 buffer_time=0.576 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 915.6: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000141 mcu_task_stddev=0.000068 bytes_write=14477 bytes_read=927608 bytes_retransmit=36 bytes_invalid=0 send_seq=1465 receive_seq=1463 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000372 heater_bed: target=0 temp=17.1 pwm=0.000  print_time=888.787 buffer_time=0.249 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
probe at 100.000,100.000 is z=0.604000
Stats 916.6: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000141 mcu_task_stddev=0.000068 bytes_write=14805 bytes_read=928717 bytes_retransmit=36 bytes_invalid=0 send_seq=1479 receive_seq=1479 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000372 heater_bed: target=0 temp=17.5 pwm=0.000  print_time=889.697 buffer_time=0.159 print_stall=0 extruder: target=0 temp=17.9 pwm=0.000
probe at 100.000,100.000 is z=0.609000
Stats 917.6: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000141 mcu_task_stddev=0.000068 bytes_write=15159 bytes_read=929858 bytes_retransmit=36 bytes_invalid=0 send_seq=1495 receive_seq=1494 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000373 heater_bed: target=0 temp=17.5 pwm=0.000  print_time=890.737 buffer_time=0.198 print_stall=0 extruder: target=0 temp=17.9 pwm=0.000
probe at 100.000,100.000 is z=0.571500
Stats 918.6: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000142 mcu_task_stddev=0.000067 bytes_write=15501 bytes_read=931019 bytes_retransmit=36 bytes_invalid=0 send_seq=1510 receive_seq=1510 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000375 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=891.734 buffer_time=0.194 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
probe at 100.000,100.000 is z=0.584000
Stats 919.6: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000142 mcu_task_stddev=0.000067 bytes_write=15800 bytes_read=932151 bytes_retransmit=36 bytes_invalid=0 send_seq=1526 receive_seq=1526 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000376 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=892.724 buffer_time=0.184 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
probe at 100.000,100.000 is z=0.551500
Stats 920.7: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000142 mcu_task_stddev=0.000067 bytes_write=16135 bytes_read=933288 bytes_retransmit=36 bytes_invalid=0 send_seq=1543 receive_seq=1543 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=28 stalled_bytes=0 freq=16000376 heater_bed: target=0 temp=17.5 pwm=0.000  print_time=893.827 buffer_time=0.285 print_stall=0 extruder: target=0 temp=18.5 pwm=0.000
probe at 100.000,100.000 is z=0.551500
Starting manual Z probe. Use TESTZ to adjust position.
Finish with ACCEPT or ABORT command.
Z position: ?????? --> 5.569 <-- ??????
passed: PROBE_CALIBRATE
Stats 921.7: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000142 mcu_task_stddev=0.000067 bytes_write=16820 bytes_read=934474 bytes_retransmit=36 bytes_invalid=0 send_seq=1567 receive_seq=1567 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=32 stalled_bytes=0 freq=16000376 heater_bed: target=0 temp=17.6 pwm=0.000  print_time=904.002 buffer_time=9.460 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 922.7: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000142 mcu_task_stddev=0.000067 bytes_write=16890 bytes_read=935522 bytes_retransmit=36 bytes_invalid=0 send_seq=1570 receive_seq=1570 retransmit_seq=17 srtt=0.004 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000375 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=904.002 buffer_time=8.459 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 923.7: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000140 mcu_task_stddev=0.000076 bytes_write=16896 bytes_read=936589 bytes_retransmit=36 bytes_invalid=0 send_seq=1571 receive_seq=1571 retransmit_seq=17 srtt=0.004 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000376 heater_bed: target=0 temp=17.5 pwm=0.000  print_time=904.002 buffer_time=7.458 print_stall=0 extruder: target=0 temp=18.0 pwm=0.000
Stats 924.7: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000140 mcu_task_stddev=0.000076 bytes_write=16902 bytes_read=937627 bytes_retransmit=36 bytes_invalid=0 send_seq=1572 receive_seq=1572 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000376 heater_bed: target=0 temp=17.6 pwm=0.000  print_time=904.002 buffer_time=6.457 print_stall=0 extruder: target=0 temp=17.9 pwm=0.000
Stats 925.7: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000140 mcu_task_stddev=0.000076 bytes_write=16908 bytes_read=938665 bytes_retransmit=36 bytes_invalid=0 send_seq=1573 receive_seq=1573 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000376 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=904.002 buffer_time=5.457 print_stall=0 extruder: target=0 temp=18.3 pwm=0.000
Stats 926.7: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000140 mcu_task_stddev=0.000076 bytes_write=16914 bytes_read=939717 bytes_retransmit=36 bytes_invalid=0 send_seq=1574 receive_seq=1574 retransmit_seq=17 srtt=0.004 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000376 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=904.002 buffer_time=4.455 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 927.7: gcodein=0 mcu: mcu_awake=0.071 mcu_task_avg=0.000140 mcu_task_stddev=0.000076 bytes_write=16920 bytes_read=940755 bytes_retransmit=36 bytes_invalid=0 send_seq=1575 receive_seq=1575 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000377 heater_bed: target=0 temp=17.4 pwm=0.000  print_time=904.002 buffer_time=3.455 print_stall=0 extruder: target=0 temp=18.0 pwm=0.000
Stats 928.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000134 mcu_task_stddev=0.000043 bytes_write=16926 bytes_read=941808 bytes_retransmit=36 bytes_invalid=0 send_seq=1576 receive_seq=1576 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000377 heater_bed: target=0 temp=17.4 pwm=0.000  print_time=904.002 buffer_time=2.454 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 929.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000134 mcu_task_stddev=0.000043 bytes_write=16932 bytes_read=942860 bytes_retransmit=36 bytes_invalid=0 send_seq=1577 receive_seq=1577 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000377 heater_bed: target=0 temp=17.4 pwm=0.000  print_time=904.002 buffer_time=1.453 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 930.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000134 mcu_task_stddev=0.000043 bytes_write=16938 bytes_read=943898 bytes_retransmit=36 bytes_invalid=0 send_seq=1578 receive_seq=1578 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.4 pwm=0.000  print_time=904.002 buffer_time=0.453 print_stall=0 extruder: target=0 temp=18.3 pwm=0.000
Stats 931.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000134 mcu_task_stddev=0.000043 bytes_write=16944 bytes_read=944936 bytes_retransmit=36 bytes_invalid=0 send_seq=1579 receive_seq=1579 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.7 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.3 pwm=0.000
Stats 932.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000134 mcu_task_stddev=0.000043 bytes_write=16982 bytes_read=945998 bytes_retransmit=36 bytes_invalid=0 send_seq=1582 receive_seq=1582 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.6 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.0 pwm=0.000
Stats 933.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000136 mcu_task_stddev=0.000051 bytes_write=16988 bytes_read=947065 bytes_retransmit=36 bytes_invalid=0 send_seq=1583 receive_seq=1583 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 934.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000136 mcu_task_stddev=0.000051 bytes_write=16994 bytes_read=948089 bytes_retransmit=36 bytes_invalid=0 send_seq=1584 receive_seq=1584 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000379 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=17.9 pwm=0.000
Stats 935.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000136 mcu_task_stddev=0.000051 bytes_write=17000 bytes_read=949155 bytes_retransmit=36 bytes_invalid=0 send_seq=1585 receive_seq=1585 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000379 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
ABORT
DWC2:89588.87 - 192.168.178.29 - GET - /rr_gcode?gcode=ABORT
ABORT
passed: ABORT
Stats 936.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000136 mcu_task_stddev=0.000051 bytes_write=17006 bytes_read=950193 bytes_retransmit=36 bytes_invalid=0 send_seq=1586 receive_seq=1586 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000379 heater_bed: target=0 temp=17.5 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 937.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000136 mcu_task_stddev=0.000051 bytes_write=17012 bytes_read=951217 bytes_retransmit=36 bytes_invalid=0 send_seq=1587 receive_seq=1587 retransmit_seq=17 srtt=0.005 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000379 heater_bed: target=0 temp=17.6 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 938.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17054 bytes_read=952318 bytes_retransmit=36 bytes_invalid=0 send_seq=1592 receive_seq=1592 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.3 pwm=0.000
Stats 939.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17060 bytes_read=953356 bytes_retransmit=36 bytes_invalid=0 send_seq=1593 receive_seq=1593 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.5 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.2 pwm=0.000
Stats 940.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17066 bytes_read=954394 bytes_retransmit=36 bytes_invalid=0 send_seq=1594 receive_seq=1594 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.5 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 941.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17072 bytes_read=955446 bytes_retransmit=36 bytes_invalid=0 send_seq=1595 receive_seq=1595 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.6 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=17.7 pwm=0.000
Stats 942.7: gcodein=0 mcu: mcu_awake=0.057 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17078 bytes_read=956484 bytes_retransmit=36 bytes_invalid=0 send_seq=1596 receive_seq=1596 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.5 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 943.7: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17084 bytes_read=957537 bytes_retransmit=36 bytes_invalid=0 send_seq=1597 receive_seq=1597 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.7 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.2 pwm=0.000
Stats 944.7: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17090 bytes_read=958589 bytes_retransmit=36 bytes_invalid=0 send_seq=1598 receive_seq=1598 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000378 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.2 pwm=0.000
Stats 945.7: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17102 bytes_read=959643 bytes_retransmit=36 bytes_invalid=0 send_seq=1600 receive_seq=1600 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000380 heater_bed: target=0 temp=17.4 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.2 pwm=0.000
Stats 946.7: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17108 bytes_read=960681 bytes_retransmit=36 bytes_invalid=0 send_seq=1601 receive_seq=1601 retransmit_seq=17 srtt=0.004 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000380 heater_bed: target=0 temp=17.2 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.1 pwm=0.000
Stats 947.7: gcodein=0 mcu: mcu_awake=0.056 mcu_task_avg=0.000133 mcu_task_stddev=0.000042 bytes_write=17114 bytes_read=961747 bytes_retransmit=36 bytes_invalid=0 send_seq=1602 receive_seq=1602 retransmit_seq=17 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000380 heater_bed: target=0 temp=17.3 pwm=0.000  print_time=904.002 buffer_time=0.000 print_stall=0 extruder: target=0 temp=18.3 pwm=0.000
`

Edit: 
deleted a stupid "discovery" about 192.168.178.29, it's my computers IP

**Comment by Stephan3** [comment]
Do you see that log you posted? it is a wall of text. Even if i like its great square geometry is it not very readable. you can attach files here.
